# Site settings
title: Andy Li's Visual Portfolio
description: Online CV
#baseurl: "/index"
#url: "https://ymlandy.github.io/portfolio/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andy Li
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Data Visualisation Enthusiast
email: andy.li.lym94@gmail.com
twitter_username: lorem_ipsum
github_username:  ymlandy
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
